spring:
  application:
    name: ApiGateWay

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: abubakar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9000

eureka:
  instance:
    # If you want to specify the IP address, use a valid one, e.g., 127.0.0.1 or remove this line
    ip-address: 127.0.0.1
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring.cloud.gateway:
  routes:
    - id: HOTEL-SERVICE
      uri: lb://HotelService   # 'lb' indicates load balancing via Eureka
      predicates:
        - Path=/hotels/**  # This matches any request to "/hotels/**"
