spring:
  application:
    name: HotelService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: abubakar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9098
 
eureka:
  instance:
    # Set a valid IP address or leave this section out for local development
    ip-address: 127.0.0.1  # Or omit this if not needed
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
