spring:
  application:
    name: RatingService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9097
 
eureka:
  instance:
    ip-address: :true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  
  